tasks:
    clone-repos:
        name: Clone additional repositories
        command: |
            [ -d spring-petclinic ] || git clone https://github.com/ona-samples/spring-petclinic
            [ -d private-market-hub ] || git clone https://github.com/ona-samples/private-market-hub
        triggeredBy: ['postDevcontainerStart', 'manual']